name: "Test Latest QEMU Version with Lima"

on:
  workflow_call:
  workflow_dispatch:

env:
  GO111MODULE: on

jobs:
  get-latest-qemu-version-commit:
    name: "Get Latest QEMU Version & Commit Hash"
    
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      qemu-version: ${{ steps.get-qemu-version-commit-hash.outputs.qemu_version }}
      qemu-commit: ${{ steps.get-qemu-version-commit-hash.outputs.qemu_commit }}

    steps:
      - name: "Get latest qemu formula version & commit hash from homebrew repo"
        id: get-qemu-version-commit-hash
        run: |
          # the git log will look like "COMMIT_HASH COMMIT_TITLE"
          # COMMIT_TITLE will contain the qemu version as X.X.X
          qemu_git_log=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/Homebrew/homebrew-core/commits?path=Formula/q/qemu.rb&per_page=1" \
          | jq -r '.[0] | "\(.sha) \(.commit.message)"')
          qemu_commit=$(echo $qemu_git_log | awk '{print $1}')
          qemu_version=$(echo $qemu_git_log | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          
          echo "qemu_version=$qemu_version" | tee -a $GITHUB_OUTPUT
          echo "qemu_commit=$qemu_commit" | tee -a $GITHUB_OUTPUT

  macos-test:
    needs: get-latest-qemu-version-commit
    name: "Test Lima VM with latest QEMU on macOS"

    permissions:
      contents: read
    
    strategy:
      matrix:
        arch: [amd64, arm64]

    runs-on: [self-hosted, macos, "${{ matrix.arch }}", 14, release]
    timeout-minutes: 60
    
    outputs:
      failed: ${{ steps.start-vms.outputs.failed }}
    
    steps:
      - name: "Checkout finch-core repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: "Install the latest qemu version"
        run: |
          brew uninstall --force qemu
          brew uninstall --force homebrew/local/qemu
          
          echo "Installing qemu version ${{ needs.get-latest-qemu-version-commit.outputs.qemu-version }}"
          HOMEBREW_LOCAL_REPO=$(brew --repository)/Library/Taps/homebrew/homebrew-local/Formula
          mkdir -p $HOMEBREW_LOCAL_REPO
          rm -f $HOMEBREW_LOCAL_REPO/qemu.rb
          curl -L -o $HOMEBREW_LOCAL_REPO/qemu.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/${{ needs.get-latest-qemu-version-commit.outputs.qemu-commit }}/Formula/q/qemu.rb
          brew install homebrew/local/qemu
          brew list --version qemu

      - name: "Setup go"
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: src/lima/go.mod

      - name: "Make lima"
        run: |
          prefix=${{ matrix.arch == 'amd64' && '/usr/local' || '/opt/homebrew' }}
          cd src/lima
          sudo make clean all install PREFIX=$prefix
          limactl --version

      - name: "Start lima vms with qemu"
        id: start-vms
        run: |
          limactl delete --force alpine || true
          limactl delete --force default || true
          
          failed=false
          if ! limactl start --tty=false --vm-type=qemu src/lima/templates/alpine.yaml; then
            echo "Failed to start alpine VM"
            failed=true
          fi
          
          if ! limactl start --tty=false --vm-type=qemu src/lima/templates/default.yaml; then
            echo "Failed to start default VM"
            failed=true
          fi
          
          echo "failed=$failed" >> $GITHUB_OUTPUT
      
      - name: "Check lima vms"
        if: steps.start-vms.outputs.failed == 'false'
        run: |
          limactl ls
          limactl shell default uname
          limactl shell alpine uname

      - name: "Clean up lima vms"
        run: |
          limactl delete --force default || true
          limactl delete --force alpine || true

      - name: "Uninstall qemu"
        run: |
          brew uninstall --force homebrew/local/qemu

  create-pr:
    needs: [get-latest-qemu-version-commit, macos-test]
    if: needs.macos-test.outputs.failed != 'true' && github.event_name != 'pull_request'
    name: "Create PR for QEMU update"
    
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Checkout finch-core repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Update qemu.conf file with new qemu version and commit hash"
        run: |
          cat > deps/qemu.conf <<EOF
          QEMU_VERSION=${{ needs.get-latest-qemu-version-commit.outputs.qemu-version }}
          QEMU_FORMULA_GH_COMMIT=${{ needs.get-latest-qemu-version-commit.outputs.qemu-commit }}
          EOF

      - name: "Create PR for qemu update"
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true
          branch: create-pull-request/bump-qemu-version
          delete-branch: true
          add-paths: deps/qemu.conf
          title: 'build(deps): update QEMU version to ${{ needs.get-latest-qemu-version-commit.outputs.qemu-version }}'
          body: |
            This PR created by [create-pull-request](https://github.com/peter-evans/create-pull-request) may need be closed 
            and reopened manually to trigger automated checks.
