name: update-ecr-cred-helper

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-ecr-cred-helper-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Get latest ECR Cred Helper Version
        id: version
        run: |
          latest_tag="$(\
            curl -sL --fail "https://api.github.com/repos/awslabs/amazon-ecr-credential-helper/releases/latest" | \
            grep '"tag_name":' | \
            head -1 | \
            cut -d'"' -f4 \
          )"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "Latest tag is ${latest_tag}"

      - name: Update .conf file
        run: |
          latest_tag="${{ steps.version.outputs.tag }}"
          AMD64_DIGEST=$(curl -sL --fail "https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/${latest_tag#v}/linux-amd64/docker-credential-ecr-login.sha256" | awk '{print $1}')
          ARM64_DIGEST=$(curl -sL --fail "https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/${latest_tag#v}/linux-arm64/docker-credential-ecr-login.sha256" | awk '{print $1}')
          
          cat > deps/ecr-cred-helper.conf << EOF
          ECR_CRED_HELPER_VERSION=${latest_tag#v}
          ECR_CRED_HELPER_AMD64_DIGEST=sha256:${AMD64_DIGEST}
          ECR_CRED_HELPER_ARM64_DIGEST=sha256:${ARM64_DIGEST}
          EOF

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet deps/ecr-cred-helper.conf; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in dependencies"
            exit 0
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in dependencies:"
            git diff deps/ecr-cred-helper.conf
          fi

      - name: Create or update PR
        if: github.event_name != 'pull_request' && steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true
          commit-message: 'chore: update ecr-cred-helper'
          title: 'chore: update ecr-cred-helper'
          body: |
            This PR updates ecr-cred-helper to the latest version
            This is an automated update created by the dependency update workflow. Review the changes before approving.
          branch: update-ecr-cred-helper
          delete-branch: true
